-- =====================================================================
-- 003 — Catálogo de barrios de Bosa (ADR-0016)
--
-- GENERADO por `python -m scripts.generar_catalogo_barrios` desde el
-- listado oficial de barrios de Bogotá por localidad. No se edita a mano.
--
-- Sustituye a los siete barrios de la UPZ 84 que sembraba `002`, que se
-- calibraron contra el anteproyecto §5.3.1. Dos correcciones respecto de
-- aquel:
--
--  - `Los 3 Sectores` NO entra: no aparece en el listado oficial, ni
--    exacta ni parcialmente. El ADR-0002 lo había sembrado resolviendo a
--    favor del §5.3.1 frente al §7.1, que lo omitía; el listado indica
--    que era el §7.1 el que acertaba, y que §5.3.1 recogía un nombre de
--    uso comunitario y no un barrio oficial.
--  - El alcance pasa de la UPZ 84 Bosa Occidental a la localidad entera.
--    Es deliberado: tener de más un barrio cuesta una fila, y que falte
--    cuesta una usuaria que no puede completar el onboarding.
--
-- Los nombres van en MAYÚSCULA y sin recortar, tal como vienen del
-- listado oficial. No hay límite de longitud que obligue a acortarlos: la
-- desambiguación se presenta como lista numerada en el cuerpo de un
-- mensaje —1024 caracteres— y no como botones, cuyo rótulo se queda en 20
-- (ADR-0016, decisión 4).
--
-- `otro` se conserva. Es la salida cuando ninguno de los candidatos es su
-- barrio, y sin él la pregunta del barrio no tendría fin, porque es
-- obligatoria (ADR-0002 y ADR-0016, decisión 6).
--
-- Idempotente: puede reejecutarse sin duplicar filas. El `do update`
-- —y no `do nothing`, que es lo que hacía 002— es necesario porque un
-- código que ya exista tiene que quedar con el nombre y el `activo` de
-- este listado; con `do nothing` la fila vieja sobreviviría intacta.
-- =====================================================================

insert into public.barrio (codigo, nombre) values
    ('amaruc', 'AMARUC'),
    ('andalucia', 'ANDALUCIA'),
    ('andalucia_ii', 'ANDALUCIA II'),
    ('antonia_santos', 'ANTONIA SANTOS'),
    ('antonio_narino', 'ANTONIO NARIÑO'),
    ('argelia', 'ARGELIA'),
    ('argelia_ii', 'ARGELIA II'),
    ('berlin', 'BERLIN'),
    ('berlin_de_bosa_la_libertad_iii', 'BERLIN DE BOSA LA LIBERTAD III'),
    ('betania', 'BETANIA'),
    ('bosa', 'BOSA'),
    ('bosa_nova', 'BOSA NOVA'),
    ('bosa_nova_ii_sector', 'BOSA NOVA II SECTOR'),
    ('bosalinda_hildebrando_olarte', 'BOSALINDA (HILDEBRANDO OLARTE)'),
    ('bosques_de_meryland', 'BOSQUES DE MERYLAND'),
    ('brasil_ii_sector', 'BRASIL II SECTOR'),
    ('brasil_ii_segunda_etapa', 'BRASIL II SEGUNDA ETAPA'),
    ('brasil_lopez_y_pineros', 'BRASIL LOPEZ Y PIÑEROS'),
    ('brasil_materas_acacias_s_jorge', 'BRASIL MATERAS ACACIAS S.JORGE'),
    ('brasil_sector_barreto', 'BRASIL SECTOR BARRETO'),
    ('brasil_sector_portal_y_castillo', 'BRASIL SECTOR PORTAL Y CASTILLO'),
    ('brasilia_2_sector', 'BRASILIA 2° SECTOR'),
    ('brasilia_3_sector', 'BRASILIA 3° SECTOR'),
    ('brasilia_i_sector', 'BRASILIA I SECTOR'),
    ('brasilia_la_estacion', 'BRASILIA LA ESTACION'),
    ('caldas', 'CALDAS'),
    ('campo_hermoso', 'CAMPO HERMOSO'),
    ('carlos_alban_holguin_nueva_granada', 'CARLOS ALBAN HOLGUIN NUEVA GRANADA'),
    ('carlos_alban_sector_israelita', 'CARLOS ALBAN SECTOR ISRAELITA'),
    ('carlos_alban_sector_miraflores', 'CARLOS ALBAN SECTOR MIRAFLORES'),
    ('carlos_galban', 'CARLOS GALBÁN'),
    ('casa_nueva', 'CASA NUEVA'),
    ('canaveralejo', 'CAÑAVERALEJO'),
    ('charles_de_gaulle', 'CHARLES DE GAULLE'),
    ('charles_de_gaulle_ii', 'CHARLES DE GAULLE II'),
    ('chico_sur', 'CHICO SUR'),
    ('chiicala', 'CHIICALA'),
    ('ciudadela_la_libertad_ii', 'CIUDADELA LA LIBERTAD II'),
    ('claretiano', 'CLARETIANO'),
    ('danubio', 'DANUBIO'),
    ('danubio_azul_i', 'DANUBIO AZUL I'),
    ('danubio_ii', 'DANUBIO II'),
    ('danubio_iii', 'DANUBIO III'),
    ('diamante_sur', 'DIAMANTE SUR'),
    ('divino_nino', 'DIVINO NIÑO'),
    ('el_anhelo', 'EL ANHELO'),
    ('el_bosque_de_bosa', 'EL BOSQUE DE BOSA'),
    ('el_cauce', 'EL CAUCE'),
    ('el_corzo', 'EL CORZO'),
    ('el_diamante', 'EL DIAMANTE'),
    ('el_jardin', 'EL JARDIN'),
    ('el_jardin_san_eugenio', 'EL JARDÍN SAN EUGENIO'),
    ('el_jazmin_sector_el_triangulo', 'EL JAZMIN SECTOR EL TRIANGULO'),
    ('el_libertador', 'EL LIBERTADOR'),
    ('el_libertador_ii', 'EL LIBERTADOR II'),
    ('el_llanito', 'EL LLANITO'),
    ('el_llano_sector_guzman', 'EL LLANO (SECTOR GUZMAN)'),
    ('el_llano_mz_a', 'EL LLANO MZ A'),
    ('el_llano_sector_fandino', 'EL LLANO SECTOR FANDINO'),
    ('el_matorral', 'EL MATORRAL'),
    ('el_matorral_de_san_bernardino', 'EL MATORRAL DE SAN BERNARDINO'),
    ('el_motorista', 'EL MOTORISTA'),
    ('el_palmar', 'EL PALMAR'),
    ('el_paradero', 'EL PARADERO'),
    ('el_paraiso', 'EL PARAISO'),
    ('el_portal_de_bosa', 'EL PORTAL DE BOSA'),
    ('el_portal_de_la_libertad_1', 'EL PORTAL DE LA LIBERTAD 1'),
    ('el_portal_i_y_ii_sector', 'EL PORTAL I y II SECTOR'),
    ('el_porvenir', 'EL PORVENIR'),
    ('el_porvenir_ii_sector', 'EL PORVENIR II SECTOR'),
    ('el_porvenir_iii', 'EL PORVENIR III'),
    ('el_porvenir_parcela_23', 'EL PORVENIR PARCELA 23'),
    ('el_porvenir_san_luis', 'EL PORVENIR SAN LUIS'),
    ('el_porvenir_sector_brasil', 'EL PORVENIR SECTOR BRASIL'),
    ('el_porvenir_sector_inducas', 'EL PORVENIR SECTOR INDUCAS'),
    ('el_progreso', 'EL PROGRESO'),
    ('el_progreso_ii_sector', 'EL PROGRESO II SECTOR'),
    ('el_recuerdo', 'EL RECUERDO'),
    ('el_recuerdo_4_a_5_6_7', 'EL RECUERDO 4 A , 5, 6, 7'),
    ('el_recuerdo_de_santa_fe', 'EL RECUERDO DE SANTA FE'),
    ('el_recuerdo_ii', 'EL RECUERDO II'),
    ('el_recuerdo_san_bernardino', 'EL RECUERDO SAN BERNARDINO'),
    ('el_regalo', 'EL REGALO'),
    ('el_regalo_ii', 'EL REGALO II'),
    ('el_retazo', 'EL RETAZO'),
    ('el_rincon_de_bosa', 'EL RINCON DE BOSA'),
    ('el_rodeo', 'EL RODEO'),
    ('el_rubi', 'EL RUBI'),
    ('el_sauce', 'EL SAUCE'),
    ('el_toche', 'EL TOCHE'),
    ('el_triangulo_sector_materas', 'EL TRIANGULO SECTOR MATERAS'),
    ('el_triunfo', 'EL TRIUNFO'),
    ('el_triunfo_de_san_bernardino', 'EL TRIUNFO DE SAN BERNARDINO'),
    ('escocia_ix', 'ESCOCIA IX'),
    ('escocia_v', 'ESCOCIA V'),
    ('escocia_vi_sectores_i_ii_iii', 'ESCOCIA VI SECTORES I, II, III'),
    ('escocia_vii', 'ESCOCIA VII'),
    ('finca_la_esperanza', 'FINCA LA ESPERANZA'),
    ('getsemani', 'GETSEMANI'),
    ('grancolombiano_i', 'GRANCOLOMBIANO I'),
    ('grancolombiano_ii_laures_mz_l3_m_n_p_q', 'GRANCOLOMBIANO II LAURES MZ L3,M,N,P,Q'),
    ('grancolombiano_ii_sector', 'GRANCOLOMBIANO II SECTOR'),
    ('gualoche', 'GUALOCHE'),
    ('hermanos_barragan', 'HERMANOS BARRAGAN'),
    ('holanda', 'HOLANDA'),
    ('holanda_i_sector', 'HOLANDA I SECTOR'),
    ('holanda_ii_sector', 'HOLANDA II SECTOR'),
    ('holanda_iii_sector', 'HOLANDA III SECTOR'),
    ('holanda_sector_caminito', 'HOLANDA SECTOR CAMINITO'),
    ('hortelanos_de_escocia', 'HORTELANOS DE ESCOCIA'),
    ('humberto_valencia', 'HUMBERTO VALENCIA'),
    ('humberto_valencia_ii', 'HUMBERTO VALENCIA II'),
    ('industrial', 'INDUSTRIAL'),
    ('islandia', 'ISLANDIA'),
    ('islandia_ii', 'ISLANDIA II'),
    ('islandia_iii', 'ISLANDIA III'),
    ('islandia_iv', 'ISLANDIA IV'),
    ('israelita', 'ISRAELITA'),
    ('jardines_del_apogeo', 'JARDINES DEL APOGEO'),
    ('jimenez_de_quesada', 'JIMENEZ DE QUESADA'),
    ('jimenez_de_quesada_ii_sector', 'JIMENEZ DE QUESADA II SECTOR'),
    ('jorge_uribe_botero', 'JORGE URIBE BOTERO'),
    ('jose_antonio_galan', 'JOSE ANTONIO GALAN'),
    ('jose_maria_carbonel_i_y_ii_sector', 'JOSE MARIA CARBONEL I Y II SECTOR'),
    ('la_amistad', 'LA AMISTAD'),
    ('la_arboleda', 'LA ARBOLEDA'),
    ('la_aurora', 'LA AURORA'),
    ('la_azucena', 'LA AZUCENA'),
    ('la_azucena_mz_a', 'LA AZUCENA MZ.A'),
    ('la_azucena_mz_b', 'LA AZUCENA MZ.B'),
    ('la_azucena_sector_el_triangulo', 'LA AZUCENA SECTOR EL TRIANGULO'),
    ('la_cabana', 'LA CABAÑA'),
    ('la_concepcion', 'LA CONCEPCION'),
    ('la_concepcion_ii_sector', 'LA CONCEPCION II SECTOR'),
    ('la_cruz_de_terreros', 'LA CRUZ DE TERREROS'),
    ('la_dulcinea', 'LA DULCINEA'),
    ('la_ele_ii_sector_los_laureles', 'LA ELE II SECTOR LOS LAURELES'),
    ('la_esmeralda', 'LA ESMERALDA'),
    ('la_esperanza_de_tibanica', 'LA ESPERANZA DE TIBANICA'),
    ('la_esperanza_i', 'LA ESPERANZA I'),
    ('la_esperanza_ii_sector', 'LA ESPERANZA II SECTOR'),
    ('la_estacion', 'LA ESTACION'),
    ('la_estacion_areneras', 'LA ESTACION ARENERAS'),
    ('la_estacion_distrital_fca_raiz', 'LA ESTACION DISTRITAL FCA RAIZ'),
    ('la_estanzuela', 'LA ESTANZUELA'),
    ('la_estanzuela_ii', 'LA ESTANZUELA II'),
    ('la_florida_iv_sector', 'LA FLORIDA IV SECTOR'),
    ('la_fontana_de_bosa_la_libertad', 'LA FONTANA DE BOSA LA LIBERTAD'),
    ('la_fontana_i_y_ii', 'LA FONTANA I Y II'),
    ('la_granjita', 'LA GRANJITA'),
    ('la_ilusion', 'LA ILUSION'),
    ('la_independencia', 'LA INDEPENDENCIA'),
    ('la_independencia_ii_sector', 'LA INDEPENDENCIA II SECTOR'),
    ('la_libertad', 'LA LIBERTAD'),
    ('la_libertad_ii', 'LA LIBERTAD II'),
    ('la_libertad_iii', 'LA LIBERTAD III'),
    ('la_libertad_iv', 'LA LIBERTAD IV'),
    ('la_libertad_sector_magnolia', 'LA LIBERTAD SECTOR MAGNOLIA'),
    ('la_magnolia_ii', 'LA MAGNOLIA II'),
    ('la_maria', 'LA MARIA'),
    ('la_palestina_i', 'LA PALESTINA I'),
    ('la_palma', 'LA PALMA'),
    ('la_paz', 'LA PAZ'),
    ('la_paz_ii_sector', 'LA PAZ II SECTOR'),
    ('la_paz_iii', 'LA PAZ III'),
    ('la_paz_san_ignacio_las_vegas', 'LA PAZ SAN IGNACIO LAS VEGAS'),
    ('la_paz_san_ignacio_sec_la_esperanza', 'LA PAZ SAN IGNACIO SEC LA ESPERANZA'),
    ('la_portada', 'LA PORTADA'),
    ('la_portada_ii', 'LA PORTADA II'),
    ('la_portada_iii_sector', 'LA PORTADA III SECTOR'),
    ('la_portadita', 'LA PORTADITA'),
    ('la_primavera', 'LA PRIMAVERA'),
    ('la_riviera_ii', 'LA RIVIERA II'),
    ('la_suerte', 'LA SUERTE'),
    ('la_sultana', 'LA SULTANA'),
    ('la_union', 'LA UNION'),
    ('la_vega_de_san_bernardino_bajo', 'LA VEGA DE SAN BERNARDINO BAJO'),
    ('la_veguita', 'LA VEGUITA'),
    ('la_veguita_ii', 'LA VEGUITA II'),
    ('la_veguita_iv_sector', 'LA VEGUITA IV SECTOR'),
    ('las_margaritas', 'LAS MARGARITAS'),
    ('las_margaritas_iii', 'LAS MARGARITAS III'),
    ('las_margaritas_sect_i_y_ii', 'LAS MARGARITAS SECT I y II'),
    ('las_soltanas', 'LAS SOLTANAS'),
    ('las_vegas', 'LAS VEGAS'),
    ('laureles_iii', 'LAURELES III'),
    ('laureles_la_estacion', 'LAURELES LA ESTACION'),
    ('llano_oriental', 'LLANO ORIENTAL'),
    ('llanos_de_bosa', 'LLANOS DE BOSA'),
    ('los_centauros', 'LOS CENTAUROS'),
    ('los_heroes', 'LOS HEROES'),
    ('los_ocales', 'LOS OCALES'),
    ('los_sauces', 'LOS SAUCES'),
    ('los_sauces_sector_cedro', 'LOS SAUCES SECTOR CEDRO'),
    ('manzanares', 'MANZANARES'),
    ('miami', 'MIAMI'),
    ('miraflores_ii_sector', 'MIRAFLORES II SECTOR'),
    ('mitrani', 'MITRANI'),
    ('naranjos_el_retazo', 'NARANJOS EL RETAZO'),
    ('new_jersey', 'NEW JERSEY'),
    ('nicolas_escobar', 'NICOLAS ESCOBAR'),
    ('nta_sra_de_la_paz_la_esperanza', 'NTA SRA DE LA PAZ - LA ESPERANZA'),
    ('ntra_senora_de_la_paz_iv_sec', 'NTRA. SEÑORA DE LA PAZ IV SEC.'),
    ('ntra_sra_de_la_paza_villa_esmeralda', 'NTRA.SRA. DE LA PAZA VILLA ESMERALDA'),
    ('nuestra_senora_de_la_paz_y_otros', 'NUESTRA SEÑORA DE LA PAZ y OTROS'),
    ('nueva_escocia', 'NUEVA ESCOCIA'),
    ('nueva_esperanza', 'NUEVA ESPERANZA'),
    ('nueva_granada', 'NUEVA GRANADA'),
    ('nueva_granada_ii_sec_tiboli', 'NUEVA GRANADA II SEC.(Tiboli)'),
    ('nueva_granada_ii_sector', 'NUEVA GRANADA II SECTOR'),
    ('nueva_granada_v_sector', 'NUEVA GRANADA V SECTOR'),
    ('nuevo_chile', 'NUEVO CHILE'),
    ('olarte', 'OLARTE'),
    ('osorio_x', 'OSORIO X'),
    ('osorio_xiii', 'OSORIO XIII'),
    ('pablo_vi', 'PABLO VI'),
    ('palestina', 'PALESTINA'),
    ('parcela_el_porvenir', 'PARCELA EL PORVENIR'),
    ('paso_ancho', 'PASO ANCHO'),
    ('piamonte_i_etapa', 'PIAMONTE I ETAPA'),
    ('porvenir_la_concepcion', 'PORVENIR LA CONCEPCION'),
    ('porvenir_par_33', 'PORVENIR PAR.33'),
    ('porvenir_parc_17a_y_17b', 'PORVENIR PARC.17A Y 17B'),
    ('potreritos', 'POTRERITOS'),
    ('primavera_sur', 'PRIMAVERA SUR'),
    ('providencia', 'PROVIDENCIA'),
    ('san_antonio', 'SAN ANTONIO'),
    ('san_antonio_de_bosa', 'SAN ANTONIO DE BOSA'),
    ('san_antonio_de_escocia', 'SAN ANTONIO DE ESCOCIA'),
    ('san_antonio_de_escocia_ii', 'SAN ANTONIO DE ESCOCIA II'),
    ('san_bernardino', 'SAN BERNARDINO'),
    ('san_bernardino_ii', 'SAN BERNARDINO II'),
    ('san_bernardino_sector_ii', 'SAN BERNARDINO SECTOR II'),
    ('san_bernardino_sector_potrerito', 'SAN BERNARDINO SECTOR POTRERITO'),
    ('san_bernardino_sector_protrerito', 'SAN BERNARDINO SECTOR PROTRERITO'),
    ('san_bernardino_sector_villa_emma', 'SAN BERNARDINO SECTOR VILLA EMMA'),
    ('san_bernardino_xix', 'SAN BERNARDINO XIX'),
    ('san_bernardino_xvi', 'SAN BERNARDINO XVI'),
    ('san_bernardino_xvii', 'SAN BERNARDINO XVII'),
    ('san_bernardino_xviii', 'SAN BERNARDINO XVIII'),
    ('san_bernardino_xxii', 'SAN BERNARDINO XXII'),
    ('san_bernardino_xxv', 'SAN BERNARDINO XXV'),
    ('san_diego_la_paz_iv_sector', 'SAN DIEGO LA PAZ IV SECTOR'),
    ('san_eugenio', 'SAN EUGENIO'),
    ('san_eugenio_ii', 'SAN EUGENIO II'),
    ('san_fernando_n_s_de_la_paz', 'SAN FERNANDO N.S. DE LA PAZ'),
    ('san_javier', 'SAN JAVIER'),
    ('san_joaquin', 'SAN JOAQUIN'),
    ('san_jorge', 'SAN JORGE'),
    ('san_jorge_ii', 'SAN JORGE II'),
    ('san_jose_los_naranjos', 'SAN JOSÉ LOS NARANJOS'),
    ('san_juanito', 'SAN JUANITO'),
    ('san_judas_b_la_estacion', 'SAN JUDAS (B.LA ESTACION)'),
    ('san_luis', 'SAN LUIS'),
    ('san_luis_ii', 'SAN LUIS II'),
    ('san_martin', 'SAN MARTIN'),
    ('san_miguel', 'SAN MIGUEL'),
    ('san_pablo', 'SAN PABLO'),
    ('san_pablo_i_sector', 'SAN PABLO I SECTOR'),
    ('san_pablo_ii_sector', 'SAN PABLO II SECTOR'),
    ('san_pedro', 'SAN PEDRO'),
    ('san_pedro_ii', 'SAN PEDRO II'),
    ('san_pedro_ii_sector_a', 'SAN PEDRO II SECTOR A'),
    ('san_pedro_sector_c', 'SAN PEDRO SECTOR "C"'),
    ('santa_barbara', 'SANTA BARBARA'),
    ('santa_fe', 'SANTA FE'),
    ('santa_fe_i_y_ii', 'SANTA FE I y II'),
    ('santa_fe_iii_sector', 'SANTA FE III SECTOR'),
    ('santa_ines', 'SANTA INES'),
    ('santa_isabel', 'SANTA ISABEL'),
    ('santa_lucia', 'SANTA LUCIA'),
    ('santafe_de_bosa', 'SANTAFE DE BOSA'),
    ('sauces_ii', 'SAUCES II'),
    ('siracuza', 'SIRACUZA'),
    ('siracuza_ii', 'SIRACUZA II'),
    ('sub_sta_lucia', 'SUB STA LUCIA'),
    ('sub_triangulo_las_materas', 'SUB TRIANGULO LAS MATERAS'),
    ('sub_urb_claretiana', 'SUB URB. CLARETIANA'),
    ('tierra_gratis', 'TIERRA GRATIS'),
    ('tokio', 'TOKIO'),
    ('urb_acuarela_i_y_ii', 'URB ACUARELA I Y II'),
    ('urb_tanque_de_bosa', 'URB. TANQUE DE BOSA'),
    ('urbanizacion_caldas', 'URBANIZACION CALDAS'),
    ('vegas_de_santana', 'VEGAS DE SANTANA'),
    ('verd_sector_san_jose', 'VERD. SECTOR SAN JOSÉ'),
    ('vereda_el_porvenir_sector_brasil', 'VEREDA EL PORVENIR SECTOR BRASIL'),
    ('villa_alegre', 'VILLA ALEGRE'),
    ('villa_alegria', 'VILLA ALEGRIA'),
    ('villa_anay', 'VILLA ANAY'),
    ('villa_anni_bosa_naranjos', 'VILLA ANNI (BOSA NARANJOS)'),
    ('villa_bosa', 'VILLA BOSA'),
    ('villa_carolina', 'VILLA CAROLINA'),
    ('villa_clemencia', 'VILLA CLEMENCIA'),
    ('villa_clemencia_sector_tierra_grata', 'VILLA CLEMENCIA SECTOR TIERRA GRATA'),
    ('villa_colombia', 'VILLA COLOMBIA'),
    ('villa_colombia_ii', 'VILLA COLOMBIA II'),
    ('villa_de_los_comuneros', 'VILLA DE LOS COMUNEROS'),
    ('villa_de_suaita', 'VILLA DE SUAITA'),
    ('villa_esmeralda', 'VILLA ESMERALDA'),
    ('villa_karen', 'VILLA KAREN'),
    ('villa_magda', 'VILLA MAGDA'),
    ('villa_magnolia', 'VILLA MAGNOLIA'),
    ('villa_natalia', 'VILLA NATALIA'),
    ('villa_nohora', 'VILLA NOHORA'),
    ('villa_nohora_ii', 'VILLA NOHORA II'),
    ('villa_nohora_iii', 'VILLA NOHORA III'),
    ('villa_sonia_i', 'VILLA SONIA I'),
    ('villa_sonia_ii', 'VILLA SONIA II'),
    ('villas_del_progreso', 'VILLAS DEL PROGRESO'),
    ('villas_del_rio', 'VILLAS DEL RIO'),
    ('villas_del_velero', 'VILLAS DEL VELERO'),
    ('xochimilco', 'XOCHIMILCO'),
    ('otro', 'Otro')
on conflict (codigo) do update
        set nombre = excluded.nombre,
            activo = true;
